-- return {
--     {
--         "nvim-treesitter/nvim-treesitter",
--         opts = {
--           ensure_installed = {
--             "bash",
--             "html",
--             "javascript",
--             "json",
--             "lua",
--             "markdown",
--             "markdown_inline",
--             "query",
--             "regex",
--             "vim",
--             "yaml",
--           },
--         },
--       },
-- }